const rooms = [
  {
    "id": 1,
    "hotel_id": 1,
    "room_number": "101",
    "type": "Deluxe",
    "price": 200.00,
    "description": "A deluxe room with sea view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Sea View", "Room Service"],
    "floor": 1,
    "beds": 2,
    "max_guests": 4,
    "size": 30,
    "images": [
      "/Images/rooms/1/1.png",
      "/Images/rooms/1/2.png",
      "/Images/rooms/1/3.png",
    ],
    "promotion": true,
    "new_price": 170.00
  },
  {
    "id": 2,
    "hotel_id": 1,
    "room_number": "102",
    "type": "Standard",
    "price": 150.00,
    "description": "A standard room with garden view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Garden View"],
    "floor": 1,
    "beds": 1,
    "max_guests": 2,
    "size": 25,
    "images": [
      "/Images/rooms/2/1.png",
      "/Images/rooms/2/2.png",
      "/Images/rooms/2/3.png",
    ],
  },
  {
    "id": 3,
    "hotel_id": 1,
    "room_number": "103",
    "type": "Suite",
    "price": 300.00,
    "description": "A luxurious suite with sea view.",
    "availability": false,
    "amenities": ["Wi-Fi", "Air Conditioning", "Sea View", "Hot Tub"],
    "floor": 1,
    "beds": 3,
    "max_guests": 6,
    "size": 45,
    "images": [
      "/Images/rooms/3/1.png",
      "/Images/rooms/3/2.png",
      "/Images/rooms/3/3.png",
    ],
    "promotion": true,
    "new_price": 255.00
  },
  {
    "id": 4,
    "hotel_id": 1,
    "room_number": "104",
    "type": "Economy",
    "price": 100.00,
    "description": "A budget-friendly room with basic amenities.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning"],
    "floor": 1,
    "beds": 1,
    "max_guests": 2,
    "size": 20,
    "images": [
      "/Images/rooms/4/1.png",
      "/Images/rooms/4/2.png",
      "/Images/rooms/4/3.png",
    ],
  },
  {
    "id": 5,
    "hotel_id": 1,
    "room_number": "105",
    "type": "Family",
    "price": 250.00,
    "description": "A spacious family room with garden view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Garden View", "Room Service"],
    "floor": 1,
    "beds": 2,
    "max_guests": 5,
    "size": 35,
    "images": [
      "/Images/rooms/5/1.png",
      "/Images/rooms/5/2.png",
      "/Images/rooms/5/3.png",
    ],
  },
  {
    "id": 6,
    "hotel_id": 2,
    "room_number": "201",
    "type": "Deluxe",
    "price": 220.00,
    "description": "A deluxe room with mountain view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Mountain View", "Room Service"],
    "floor": 2,
    "beds": 2,
    "max_guests": 4,
    "size": 32,
    "images": [
      "/Images/rooms/6/1.png",
      "/Images/rooms/6/2.png",
      "/Images/rooms/6/3.png",
    ],
  },
  {
    "id": 7,
    "hotel_id": 2,
    "room_number": "202",
    "type": "Standard",
    "price": 160.00,
    "description": "A standard room with city view.",
    "availability": false,
    "amenities": ["Wi-Fi", "Air Conditioning", "City View"],
    "floor": 2,
    "beds": 1,
    "max_guests": 2,
    "size": 28,
    "images": [
      "/Images/rooms/7/1.png",
      "/Images/rooms/7/2.png",
      "/Images/rooms/7/3.png",
    ],
    "promotion": true,
    "new_price": 136.00
  },
  {
    "id": 8,
    "hotel_id": 2,
    "room_number": "203",
    "type": "Suite",
    "price": 350.00,
    "description": "A luxurious suite with mountain view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Mountain View", "Hot Tub"],
    "floor": 2,
    "beds": 3,
    "max_guests": 6,
    "size": 50,
    "images": [
      "/Images/rooms/8/1.png",
      "/Images/rooms/8/2.png",
      "/Images/rooms/8/3.png",
    ],
  },
  {
    "id": 9,
    "hotel_id": 2,
    "room_number": "204",
    "type": "Economy",
    "price": 120.00,
    "description": "A budget-friendly room with basic amenities.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning"],
    "floor": 2,
    "beds": 1,
    "max_guests": 2,
    "size": 22,
    "images": [
      "/Images/rooms/9/1.png",
      "/Images/rooms/9/2.png",
      "/Images/rooms/9/3.png",
    ],
  },
  {
    "id": 10,
    "hotel_id": 2,
    "room_number": "205",
    "type": "Family",
    "price": 280.00,
    "description": "A spacious family room with mountain view.",
    "availability": false,
    "amenities": ["Wi-Fi", "Air Conditioning", "Mountain View", "Room Service"],
    "floor": 2,
    "beds": 2,
    "max_guests": 5,
    "size": 38,
    "images": [
      "/Images/rooms/10/1.png",
      "/Images/rooms/10/2.png",
      "/Images/rooms/10/3.png",
    ],
  },
  {
    "id": 11,
    "hotel_id": 3,
    "room_number": "301",
    "type": "Deluxe",
    "price": 230.00,
    "description": "A deluxe room with garden view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Garden View", "Room Service"],
    "floor": 3,
    "beds": 2,
    "max_guests": 4,
    "size": 33,
    "images": [
      "/Images/rooms/11/1.png",
      "/Images/rooms/11/2.png",
      "/Images/rooms/11/3.png",
    ],
    "promotion": true,
    "new_price": 155.50
  },
  {
    "id": 12,
    "hotel_id": 3,
    "room_number": "302",
    "type": "Standard",
    "price": 170.00,
    "description": "A standard room with pool view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Pool View"],
    "floor": 3,
    "beds": 1,
    "max_guests": 2,
    "size": 27,
    "images": [
      "/Images/rooms/12/1.png",
      "/Images/rooms/12/2.png",
      "/Images/rooms/12/3.png",
    ],
  },
  {
    "id": 13,
    "hotel_id": 3,
    "room_number": "303",
    "type": "Suite",
    "price": 370.00,
    "description": "A luxurious suite with garden view.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning", "Garden View", "Hot Tub"],
    "floor": 3,
    "beds": 3,
    "max_guests": 6,
    "size": 55,
    "images": [
      "/Images/rooms/13/1.png",
      "/Images/rooms/13/2.png",
      "/Images/rooms/13/3.png",
    ],
  },
  {
    "id": 14,
    "hotel_id": 3,
    "room_number": "304",
    "type": "Economy",
    "price": 130.00,
    "description": "A budget-friendly room with basic amenities.",
    "availability": true,
    "amenities": ["Wi-Fi", "Air Conditioning"],
    "floor": 3,
    "beds": 1,
    "max_guests": 2,
    "size": 24,
    "images": [
      "/Images/rooms/14/1.png",
      "/Images/rooms/14/2.png",
      "/Images/rooms/14/3.png",
    ],
    "promotion": true,
    "new_price": 110.50
  },
]

export default rooms;